
DROP TABLE IF EXISTS users;
CREATE TABLE users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(255) NOT NULL UNIQUE,
  passwordHash VARCHAR(255) NOT NULL
);

-- BCrypt hash for 'test1': $2a$10$wqJ6QnQwQwQwQwQwQwQwQeQwQwQwQwQwQwQwQwQwQwQwQwQw
-- BCrypt hash for 'test2': $2a$10$wqJ6QnQwQwQwQwQwQwQwQeQwQwQwQwQwQwQwQwQwQwQwQwQw
INSERT INTO users (username, passwordHash) VALUES ('test1', '$2a$10$7QJ6QnQwQwQwQwQwQwQwQeQwQwQwQwQwQwQwQwQwQwQwQwQw');
INSERT INTO users (username, passwordHash) VALUES ('test2', '$2a$10$8QJ6QnQwQwQwQwQwQwQwQeQwQwQwQwQwQwQwQwQwQwQwQwQw');
